# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dev Kruger Blog
email: ms-kruger@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre desenvolvimento. Pequenas coisas que aprendi e ainda aprendo no meu dia a dia.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "pt-BR"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: _mathkruger
github_username:  mathkruger
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
